// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/invites/accept`. `name` is used only when the account is
 * created; `password` is the new password (at least 12 characters) or, for
 * an existing account, its current one. Answers with the invitee's
 * `Workspace` and a session cookie, like login.
 */
export type AcceptInviteRequest = { token: string, name: string | null, password: string, };
