// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonSummary } from "./PersonSummary";

export type ActorsResponse = { persons: Array<PersonSummary>, has_more: boolean, };
