// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleStatus } from "./LifecycleStatus";

/**
 * Which number of an insight result to open.
 */
export type ActorSelection = { "type": "TrendsPoint", series_index: number, 
/**
 * Bucket start, as in `TrendSeries.days`.
 */
day: string, breakdown_value: string | null, } | { "type": "FunnelStep", 
/**
 * 0-based step.
 */
step: number, 
/**
 * `true`: persons who reached `step`. `false`: persons who reached
 * `step - 1` but not `step`.
 */
converted: boolean, breakdown_value: string | null, } | { "type": "RetentionCell", cohort_date: string, interval: number, } | { "type": "LifecycleCell", status: LifecycleStatus, day: string, } | { "type": "StickinessBar", series_index: number, intervals: number, };
