// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiErrorBody } from "./ApiErrorBody";

/**
 * Uniform JSON error body: `{"error": {"code", "message", "request_id"}}`.
 */
export type ApiError = { error: ApiErrorBody, };
