// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertySource } from "./PropertySource";

export type Breakdown = { property: string, type: PropertySource, 
/**
 * Top-N values kept; the rest fold into `"$$_other"`.
 */
limit: number, };
