// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/projects/{project_id}/catalog/values?key=&type=&search=`
 */
export type CatalogValue = { value: string, count: number, };
