// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/projects/{project_id}/catalog/events?search=`
 */
export type CatalogEvent = { name: string, count: number, last_seen: string | null, };
