// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/projects/{project_id}/catalog/properties?type=event|person&search=`
 */
export type CatalogProperty = { key: string, 
/**
 * `"event"` or `"person"`.
 */
type: string, 
/**
 * `"string"`, `"number"`, `"boolean"`, `"array"`, `"object"`.
 */
property_type: string, count: number, };
