// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChartDisplay = "ActionsLineGraph" | "ActionsAreaGraph" | "ActionsBar" | "ActionsBarValue" | "ActionsTable" | "ActionsPie" | "BoldNumber";
