// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Invite } from "./Invite";

/**
 * Answer to `POST …/invites` (201). The only time the token is visible.
 */
export type CreatedInvite = { invite: Invite, 
/**
 * One-time secret. Single use, expires with the invite.
 */
token: string, 
/**
 * Dashboard path the invitee opens: `/invite/{token}`. Prefix it with the
 * address people use to reach Hoglet.
 */
path: string, };
