// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * `POST /api/organizations/{org_id}/invites`
 */
export type CreateInviteRequest = { email: string, role: Role, };
