// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Relative or absolute range, PostHog conventions.
 *
 * `date_from`: `"-24h"`, `"-7d"`, `"-4w"`, `"-3m"`, `"-1y"`, `"dStart"`
 * (today), `"mStart"` (this month), `"yStart"`, `"all"`, or an ISO 8601
 * date/datetime. `date_to`: same forms, `null` = now.
 */
export type DateRange = { date_from: string, date_to: string | null, };
