// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventRow } from "./EventRow";

/**
 * `GET /api/projects/{project_id}/events?event=&person_id=&before=&limit=`
 *
 * Newest first. `before` is an RFC 3339 timestamp; pass `next_before` back
 * to page.
 */
export type EventListResponse = { events: Array<EventRow>, next_before: string | null, };
