// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Math } from "./Math";
import type { PropertyFilter } from "./PropertyFilter";

/**
 * One event (or all events) with its own filters and aggregation.
 */
export type EventNode = { 
/**
 * Event name; `null` means every event.
 */
event: string | null, 
/**
 * Display label overriding the event name.
 */
custom_name: string | null, 
/**
 * Filters that apply to this series/step only.
 */
properties: Array<PropertyFilter>, math: Math, 
/**
 * Event property aggregated by the property maths (`sum`, `avg`, …).
 */
math_property: string | null, };
