// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stored event.
 */
export type EventRow = { uuid: string, event: string, distinct_id: string, person_id: string, 
/**
 * RFC 3339.
 */
timestamp: string, properties: Record<string, unknown>, };
