// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlagFilters } from "./FlagFilters";

/**
 * Body of `POST /api/projects/{project_id}/feature_flags` and
 * `PATCH /api/projects/{project_id}/feature_flags/{id}` (PATCH: all fields
 * optional except as noted).
 */
export type FeatureFlagInput = { key: string, name: string, active: boolean, filters: FlagFilters, ensure_experience_continuity: boolean, };
