// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlagFilters } from "./FlagFilters";

export type FeatureFlag = { id: number, key: string, 
/**
 * Free-text description.
 */
name: string, active: boolean, filters: FlagFilters, 
/**
 * Keep a person's value stable across `identify`.
 */
ensure_experience_continuity: boolean, created_at: string, updated_at: string, };
