// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlagVariant = { key: string, name: string | null, 
/**
 * Share of matched persons, 0–100. Variants must sum to 100.
 */
rollout_percentage: number, };
