// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlagConditionGroup } from "./FlagConditionGroup";
import type { Multivariate } from "./Multivariate";

export type FlagFilters = { groups: Array<FlagConditionGroup>, multivariate: Multivariate | null, 
/**
 * Payload per flag value: key `"true"` for boolean flags, the variant
 * key for multivariate flags.
 */
payloads: Record<string, unknown>, };
