// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyFilter } from "./PropertyFilter";

/**
 * One release condition. Matches when every person-property filter matches,
 * then admits `rollout_percentage` of those persons (null = 100).
 */
export type FlagConditionGroup = { properties: Array<PropertyFilter>, rollout_percentage: number | null, 
/**
 * Force this variant for persons matching the group.
 */
variant: string | null, };
