// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/projects/{project_id}/feature_flags/{id}/evaluate?distinct_id=`
 * — what one person gets, and why. Powers the flag page's "test a user".
 */
export type FlagEvaluation = { key: string, enabled: boolean, variant: string | null, 
/**
 * `condition_match`, `no_condition_match`, `out_of_rollout_bound`,
 * `disabled`, …
 */
reason: string, condition_index: number | null, payload: unknown, };
