// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunnelStepResult } from "./FunnelStepResult";

export type FunnelBreakdownResult = { breakdown_value: string, steps: Array<FunnelStepResult>, };
