// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Breakdown } from "./Breakdown";
import type { DateRange } from "./DateRange";
import type { EventNode } from "./EventNode";
import type { FunnelExclusion } from "./FunnelExclusion";
import type { FunnelOrder } from "./FunnelOrder";
import type { FunnelWindow } from "./FunnelWindow";
import type { PropertyFilter } from "./PropertyFilter";

export type FunnelsQuery = { 
/**
 * Funnel steps in order; `math` is ignored.
 */
series: Array<EventNode>, date_range: DateRange, properties: Array<PropertyFilter>, 
/**
 * Breaks the funnel down by a property of the first step's event
 * (first-touch attribution) or of the person.
 */
breakdown: Breakdown | null, funnel_window: FunnelWindow, funnel_order: FunnelOrder, exclusions: Array<FunnelExclusion>, };
