// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A person who performs `event` between steps `from_step` and `to_step`
 * (0-based) is excluded from the funnel.
 */
export type FunnelExclusion = { event: string, from_step: number, to_step: number, };
