// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowUnit } from "./WindowUnit";

export type FunnelWindow = { interval: number, unit: WindowUnit, };
