// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FunnelStepResult = { 
/**
 * 0-based.
 */
order: number, name: string, count: number, conversion_from_previous: number, conversion_from_start: number, dropped_off: number, average_conversion_time_s: number | null, median_conversion_time_s: number | null, };
