// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunnelBreakdownResult } from "./FunnelBreakdownResult";
import type { FunnelStepResult } from "./FunnelStepResult";
import type { HistogramBin } from "./HistogramBin";
import type { PathLink } from "./PathLink";
import type { RetentionCohort } from "./RetentionCohort";
import type { RetentionPeriod } from "./RetentionPeriod";
import type { StickinessSeries } from "./StickinessSeries";
import type { TrendSeries } from "./TrendSeries";

export type InsightResult = { "kind": "Trends", series: Array<TrendSeries>, } | { "kind": "Funnels", steps: Array<FunnelStepResult>, breakdowns: Array<FunnelBreakdownResult>, time_to_convert: Array<HistogramBin>, } | { "kind": "Retention", period: RetentionPeriod, cohorts: Array<RetentionCohort>, } | { "kind": "Lifecycle", 
/**
 * Bucket starts, RFC 3339.
 */
days: Array<string>, labels: Array<string>, new: Array<bigint>, returning: Array<bigint>, resurrecting: Array<bigint>, 
/**
 * Reported as negative counts, PostHog-style.
 */
dormant: Array<bigint>, } | { "kind": "Stickiness", series: Array<StickinessSeries>, } | { "kind": "Paths", links: Array<PathLink>, } | { "kind": "Sql", columns: Array<string>, types: Array<string>, rows: Array<Array<unknown>>, truncated: boolean, };
