// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * What the invitee sees before accepting.
 */
export type InvitePreview = { organization_name: string, email: string, role: Role, expires_at: number, 
/**
 * An account with this email exists: accepting means signing in.
 */
account_exists: boolean, };
