// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * A pending invite. The token itself is never listed.
 * `GET /api/organizations/{org_id}/invites` → `Vec<Invite>`.
 */
export type Invite = { id: string, email: string, role: Role, 
/**
 * User id of the member who created it.
 */
created_by: string, created_at: number, 
/**
 * Unix seconds; 7 days after creation.
 */
expires_at: number, };
