// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateRange } from "./DateRange";
import type { EventNode } from "./EventNode";
import type { Interval } from "./Interval";
import type { PropertyFilter } from "./PropertyFilter";

export type LifecycleQuery = { series: EventNode, date_range: DateRange, interval: Interval, properties: Array<PropertyFilter>, };
