// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregation for a trends series. Person counts are always counts of
 * *persons* (distinct ids resolved through identity merges), never raw
 * distinct ids.
 */
export type Math = "total" | "dau" | "weekly_active" | "monthly_active" | "unique_session" | "sum" | "avg" | "min" | "max" | "median" | "p90" | "p95" | "p99";
