// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * One person in an organization.
 * `GET /api/organizations/{org_id}/members` → `Vec<Member>`.
 */
export type Member = { user_id: string, name: string, email: string, role: Role, 
/**
 * Unix seconds.
 */
joined_at: number, };
