// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateRange } from "./DateRange";
import type { PathsType } from "./PathsType";
import type { PropertyFilter } from "./PropertyFilter";

export type PathsQuery = { paths_type: PathsType, 
/**
 * Only paths starting at this node (path or event name).
 */
start_point: string | null, 
/**
 * Only paths ending at this node.
 */
end_point: string | null, 
/**
 * Maximum steps per path.
 */
step_limit: number, 
/**
 * Maximum links returned (strongest first).
 */
edge_limit: number, date_range: DateRange, properties: Array<PropertyFilter>, };
