// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PathLink = { 
/**
 * Step-prefixed node names: `"1_/pricing"` → `"2_/signup"`.
 */
source: string, target: string, value: number, average_conversion_time_s: number, };
