// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonSummary } from "./PersonSummary";

/**
 * `GET /api/projects/{project_id}/persons?search=&cursor=&limit=`
 */
export type PersonListResponse = { persons: Array<PersonSummary>, 
/**
 * Opaque; pass back as `cursor` for the next page.
 */
next_cursor: string | null, };
