// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A person as listed anywhere in the UI.
 */
export type PersonSummary = { id: string, 
/**
 * `email`, then `name`, then the first distinct id.
 */
display_name: string, 
/**
 * Up to 10; the detail endpoint returns all.
 */
distinct_ids: Array<string>, properties: Record<string, unknown>, is_identified: boolean, 
/**
 * RFC 3339.
 */
created_at: string, last_seen: string | null, };
