// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/projects/{project_id}/status` — the always-visible freshness
 * signal. If numbers are behind, the product says so.
 */
export type ProjectStatus = { 
/**
 * Any event ever stored for this project.
 */
has_events: boolean, 
/**
 * Newest stored event's capture time, RFC 3339.
 */
last_event_at: string | null, 
/**
 * Seconds between the oldest acknowledged-but-unqueryable event and
 * now; 0 when everything acknowledged is queryable.
 */
ingestion_lag_seconds: number, stored_events: number, stored_bytes: number, first_day: string | null, last_day: string | null, };
