// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PostHog's property operators. `exact`/`is_not` accept a scalar or an
 * array (array = any of / none of).
 */
export type PropertyOperator = "exact" | "is_not" | "icontains" | "not_icontains" | "regex" | "not_regex" | "gt" | "gte" | "lt" | "lte" | "is_set" | "is_not_set" | "is_date_before" | "is_date_after";
