// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsightResult } from "./InsightResult";
import type { QueryMeta } from "./QueryMeta";

export type QueryResponse = { result: InsightResult, meta: QueryMeta, };
