// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsightQuery } from "./InsightQuery";

/**
 * `POST /api/projects/{project_id}/query` body.
 */
export type QueryRequest = { query: InsightQuery, 
/**
 * Bypass the result cache.
 */
refresh: boolean, };
