// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueryMeta = { kind: string, elapsed_ms: number, cached: boolean, 
/**
 * Changes whenever the project's stored events change.
 */
data_version: number, 
/**
 * Resolved absolute range, RFC 3339 UTC.
 */
date_from: string, date_to: string, timezone: string, };
