// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RetentionCohort = { 
/**
 * Cohort period start, RFC 3339.
 */
date: string, label: string, size: number, 
/**
 * `values[i]` = persons from this cohort who returned in period `i`
 * (`values[0] == size`). Periods after now are omitted.
 */
values: Array<number>, };
