// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read-only SQL over the project's events. The only relation is `events`
 * (columns: uuid, event, distinct_id, person_id, timestamp, properties, and
 * the promoted columns). `timestamp` is a UTC `TIMESTAMP`; `now_utc()` is the
 * current UTC time. Capped in rows, time and memory.
 */
export type SqlQuery = { query: string, };
