// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StickinessSeries = { label: string, series_index: number, 
/**
 * `data[i]` = persons active in exactly `i + 1` intervals of the range.
 */
data: Array<number>, labels: Array<string>, };
