// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrendSeries = { label: string, 
/**
 * Index into the query's `series`; `null` for a formula series.
 */
series_index: number | null, breakdown_value: string | null, 
/**
 * `"previous"` for the comparison period when `compare` is set.
 */
compare: string | null, 
/**
 * Bucket starts, RFC 3339.
 */
days: Array<string>, 
/**
 * Human labels for the buckets ("Mon 3 Oct", "14:00", …).
 */
labels: Array<string>, data: Array<number>, 
/**
 * Total over the range for counts; the whole-range value for
 * person-uniqueness and property maths.
 */
aggregated_value: number, };
