// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Breakdown } from "./Breakdown";
import type { ChartDisplay } from "./ChartDisplay";
import type { DateRange } from "./DateRange";
import type { EventNode } from "./EventNode";
import type { Interval } from "./Interval";
import type { PropertyFilter } from "./PropertyFilter";

export type TrendsQuery = { series: Array<EventNode>, date_range: DateRange, interval: Interval, 
/**
 * Filters applied to every series.
 */
properties: Array<PropertyFilter>, breakdown: Breakdown | null, 
/**
 * Arithmetic over series letters, e.g. `"A / B * 100"`. When set the
 * result contains the formula series instead of the raw series.
 */
formula: string | null, 
/**
 * Also return the same series for the previous period.
 */
compare: boolean, display: ChartDisplay, };
