// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * `PATCH /api/organizations/{org_id}/members/{user_id}`
 */
export type UpdateMemberRequest = { role: Role, };
