// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/projects/{project_id}/web/breakdown?dimension=&limit=` plus the
 * `WebQuery` fields.
 */
export type WebBreakdownRow = { value: string, visitors: number, views: number, 
/**
 * Percent; only for page-like dimensions.
 */
bounce_rate: number | null, };
