// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebDimension = "page" | "entry_page" | "exit_page" | "referring_domain" | "utm_source" | "utm_medium" | "utm_campaign" | "browser" | "os" | "device_type" | "country";
