// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebMetric = { value: number, 
/**
 * Same metric over the immediately preceding period of equal length.
 */
previous: number | null, };
