// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Interval } from "./Interval";
import type { WebMetric } from "./WebMetric";

/**
 * `GET /api/projects/{project_id}/web/overview`
 */
export type WebOverview = { visitors: WebMetric, pageviews: WebMetric, sessions: WebMetric, 
/**
 * Percent, 0–100.
 */
bounce_rate: WebMetric, session_duration_s: WebMetric, interval: Interval, 
/**
 * Bucket starts, RFC 3339.
 */
days: Array<string>, visitors_series: Array<number>, pageviews_series: Array<number>, 
/**
 * Persons with a pageview in the last 5 minutes.
 */
live_visitors: number, };
